# Site settings
title: CV
twitter_username: @srooj_10
name: Serajaldeen

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Email
   url: sbahamdain0009@stu.kau.edu.sa

#Any buzzword skills you want to include
skills:
 - Java
 - Matlab
 - Javascript and HTTP/CSS
 - Web designer(Amateur)
 - Android Studio
 - UML and Software Engineering Diagrams

#Education is required
education:
 - level: Computer Science student
   date: Still studying
   subject: Artificial Intelligence and Computer Science
   school: King Abdulaziz university

#This section is optional (as is the image link below)
coursera:
   profileurl:
   courses:
    - title: Programming in Java

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:

#List of interesting Github repo/projects to include - optional
github:

#Stackoverflow flair is optional
stackoverflow:

intro: |
  Computer Science student, I am experinced in Java programming and some other programming languages, I am practicing 
  designing Web pages and Android applications, I am studying to become an AI engineer.
  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
|<strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks.
